ALTER TABLE "RobotTelemetryEvent" ADD COLUMN IF NOT EXISTS "balanceUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "RobotTelemetryEvent" ADD COLUMN IF NOT EXISTS "floatMinBalanceUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
